### PR TITLE
CREATE Destinations

### LINKED ISSUE #17: CREATE Destinations
## Feature Summary

As an authenticated user
I want to `create` destinations
So that I can add destinations to the Destinations Page

## Acceptance Criteria

Given the user is on the Destinations Page
When the user clicks on the `Add New Destination` button on the DOM
Then they are redirected to a form with these fields: `name: image:`
And when the user submits the form, the data should be posted to Firebase
And the user should be returned to the Destinations Page

## Technical Requirements

- [x] Create the `Add New Destination` button.
- [x] Create the Destination form.
- [x] Make `createDestination` function to post to Firebase.

### PR DESCRIPTION
**Pull request by HunterJuneau**
## Description

- New Destination Form
- Events for Form
- Destination Post Call

## Related Issue

- #17 

## Motivation and Context

Allows the user to add new destinations.

## How Can This Be Tested?

`git fetch origin create-destinations`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by HunterJuneau** [comment]
I'm fixing conflicts now.

**Comment by HunterJuneau** [comment]
Ready for approval!

**Review by thedigitalmenagerie — APPROVED** [review]
Looks great!

**Review by cmeffley — CHANGES_REQUESTED** [review]
It's printing double cards when adding a new destination.
Possible fix is group discussion ticket #195

**Review by cmeffley — APPROVED** [review]
Looks good now

**Pull request merged**
