### PR TITLE
Update Environmental Data

### LINKED ISSUE #27: UPDATE Environmental Data
## Feature Summary

As an authenticated user
I want to `update` environmental data
So that I can update environmental data in my inventory

## Acceptance Criteria

Given the user is on the environmental data page
When the user clicks the `Update Environmental Data` button on the DOM
Then they are redirected to a form with the fields necessary to update environmental data
And when the user submits the form the data should be reset 
And the DOM should be reset 

## Technical Requirements

- [x] Add an event listener on the update button
- [x] Create an axios request to update environmental data

### PR DESCRIPTION
**Pull request by HunterJuneau**
## Description

Added a form to update environmental data.

## Related Issue

- #27 

## Motivation and Context

Allows the user to edit environmental data.

## How Can This Be Tested?

`git fetch origin update-environmental-data`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by GonzalesMatthew — CHANGES_REQUESTED** [review]
- please merge with development which has the bug fix for our second double printing issue
- also submitting edit form shows cards with no buttons afterwards

**Review by thedigitalmenagerie — APPROVED** [review]
This fix is looking good for me!

**Review by cmeffley — COMMENTED** [review]
There's double exporting of functions in environmentalData.js. I think that should be it

**Comment by HunterJuneau** [comment]
> There's double exporting of functions in environmentalData.js. I think that should be it

I'm not seeing that on my end.

**Comment by HunterJuneau** [comment]
> There's double exporting of functions in environmentalData.js. I think that should be it

Fixed!

**Review by thedigitalmenagerie — APPROVED** [review]

**Review by cmeffley — APPROVED** [review]

**Comment by HunterJuneau** [comment]
Need approval from @GonzalesMatthew

**Review by GonzalesMatthew — APPROVED** [review]

**Pull request merged**
