### PR TITLE
README updates 

### PR DESCRIPTION
**Pull request by jimguistical**
## Description
Team updated README, added new ERD, and created Netlify Deploys

## Motivation and Context

Made updates to planning docs, README, ERD, and created new Netlify deploys in order to be approved by PO to start coding.

## How Can This Be Tested?

https://development--e14-nautilus-explorer.netlify.app/

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by TrinityChristiana** [comment]
Each person should have a ticket for each milestone.
Milestone 2
- One person per ticket
- Each person should have a ticket

Milestone 3
- Missing AC "As a user, I should be able to delete a Destination from an Excursion I have created."
- One person per ticket
- Each person should have a ticket

Milestone 4
- Separate the main ticket into multiple ones (4 of them)
- One person per ticket
- Each person should have a ticket
- There can be a group ticket to look into AmCharts

**Review by fimoefive — APPROVED** [review]

**Comment by TrinityChristiana** [comment]
ERD looks great!

**Review by Mitchell-Crumbley — APPROVED** [review]

**Review by JuanDavila1101 — APPROVED** [review]
Good Job!!! Thank you

**Review by TrinityChristiana — APPROVED** [review]
😎

**Pull request merged**
