### PR TITLE
Hr createspecies

### LINKED ISSUE #30: CREATE Species
## Feature Summary

As an authenticated user
I want to `create` species
So that I can add species to my inventory 

## Acceptance Criteria

Given the user is on the species page
When the user clicks the `Add New Species` button on the DOM
Then they are redirected to a form with the fields specific to species
And when the user submits the form the data should be saved
And the DOM should be reset 

## Technical Requirements

- [ ] Add an event listener on the add species button
- [ ] Create an axios request to post a new species

### PR DESCRIPTION
**Pull request by thedigitalmenagerie**
## Description

Added create to species on click. 

## Related Issue

#30 

## Motivation and Context

This allows user to add species. 

## How Can This Be Tested?

git fetch 
git checkout hr-createspecies

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by cmeffley — APPROVED** [review]
👍

**Review by GonzalesMatthew — CHANGES_REQUESTED** [review]
Create form has two of the same form input descriptions.

**Comment by thedigitalmenagerie** [comment]
> Create form has two of the same form input descriptions.

Thanks for that catch!

**Review by GonzalesMatthew — CHANGES_REQUESTED** [review]
Styling for buttons on the log and crew pages have been modified

**Review by cmeffley — APPROVED** [review]
I believe all is fixed

**Review by HunterJuneau — CHANGES_REQUESTED** [review]
- [x] Form is submitting when clicking to the right of the `Submit Species` button.
- [x] I am able to submit empty forms.

**Review by HunterJuneau — APPROVED** [review]

**Review by GonzalesMatthew — APPROVED** [review]

**Pull request merged**
